name: hello world workflow

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo "hello world"
        shell: bash

  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub actions
        run: echo "welcome to GitHub actions"
        shell: bash

